### ISSUE TITLE
Gameplay setup wrong tab getting selected

### ISSUE THREAD

**Issue by ComputerElite** [darknight1050/questui#35]
**Issue**
The arrows to change tabs are messing up which mod shows

**Steps to reproduce**
1. Install 2 or more mods with mod settings in the song selection (I have Chroma and finger saber)
2. Go to the song selection and open the mods tab on the left
3. Select a tab, use the arrows, select another tab
You'll notice that the wrong mod settings show

**Comment by RedBrumbler** [comment]
should've been fixed around 0.12.x
