### ISSUE TITLE
[DX] Make Base64 string representation of UI elements available for use

### ISSUE THREAD

**Issue by raineaeternal** [darknight1050/questui#59]
Exactly what the title says, all projects wanting to use the QuestUI base64 stuff have been required to add it to a separate file, with the representation in it. Would be quite nice having them available without doing so. Coming from LeaderboardCore developement, I'd rather cut down on files I need, and since we have to depend on QuestUI *anyways* I feel this would be a nice QOL upgrade.

**Comment by darknight1050** [comment]
What exactly do you mean with this? Having what available without doing so?

**Comment by darknight1050** [comment]
Do you mean the stuff in QuestUI/include/Sprites?

**Comment by raineaeternal** [comment]
Yep, carats.hpp file in QuestUI/includes/Sprites.

**Comment by darknight1050** [comment]
https://github.com/darknight1050/QuestUI/commit/67e06088427cf8cdfec8481ca8c4f0adcc4a7d22
