### ISSUE TITLE
doesn't work on 1.28.0

### ISSUE THREAD

**Issue by JuanLeoson** [darknight1050/questui#75]
it needs an older version to work on 1.28.0

**Comment by darknight1050** [comment]
What version are you using (the latest one is for 1.29.0) and how exactly does it not work?

**Comment by JuanLeoson** [comment]
qmod - 1.28.0

**Comment by JuanLeoson** [comment]
it doesnt enable in questpatcher bc its says its outdated

**Comment by darknight1050** [comment]
Download the correct one for 1.28.0
